// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbw8KIe6R3Ol4bUJN39vUwS81wIGQcFjk',
    appId: '1:724125308920:android:7a00e69d5798819468680d',
    messagingSenderId: '724125308920',
    projectId: 'note-app-a8811',
    storageBucket: 'note-app-a8811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqJxJ5MNvlch9jkFMgTk39esPqTsbJiPs',
    appId: '1:724125308920:ios:576d8e65a3a4a53b68680d',
    messagingSenderId: '724125308920',
    projectId: 'note-app-a8811',
    storageBucket: 'note-app-a8811.firebasestorage.app',
    androidClientId: '724125308920-p89r2hadrdu29kbq6omp92h855raaeh5.apps.googleusercontent.com',
    iosClientId: '724125308920-o75dnph91llpat28rof1suh2v44ive15.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

}